name: Generate IPK Repository Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gzip tar coreutils

    - name: Create necessary directories
      run: |
        mkdir -p ./repo/IPK_files
        mkdir -p ./repo/usign/build
        mkdir -p ./keys
        mkdir -p ./output

    - name: Copy precompiled usign binary
      run: |
        cp ./usign/build/usign ./repo/usign/build/usign

    - name: Set execute permissions for usign
      run: |
        chmod +x ./repo/usign/build/usign

    - name: Write private key from secret
      run: |
        echo "${{ secrets.USIGN_PRIVATE_KEY }}" > ./keys/openWrtUsign.key
      env:
        USIGN_PRIVATE_KEY: ${{ secrets.USIGN_PRIVATE_KEY }}

    - name: Debug private key
      run: |
        echo "Contents of the private key file:"
        cat ./keys/openWrtUsign.key

    - name: Run IPK repository generator script
      run: |
        chmod +x ./scripts/gen_repo_files.sh
        ./scripts.gen_repo_files.sh

    - name: Debug usign command
      run: |
        echo "Attempting to sign the Packages file..."
        ./repo/usign/build/usign -S -m ./output/Packages -s ./keys/openWrtUsign.key -x ./output/Packages.sig || echo "usign failed with exit code $?"
        echo "Contents of the output directory after signing attempt:"
        ls -l ./output
        echo "Contents of the generated Packages.sig file (if created):"
        cat ./output/Packages.sig || echo "Packages.sig file does not exist"

    - name: Upload generated files
      uses: actions/upload-artifact@v2
      with:
        name: repo-files
        path: ./output/
