name: Generate IPK Repository Files

on:
  workflow_dispatch:
  push:
    paths:
      - '**.ipk'

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate matrix paths
      id: generate-matrix
      run: |
        paths=$(bash ./generate_matrix_paths.sh)
        echo "matrix=$paths" >> $GITHUB_ENV
        echo "matrix=$paths" >> $GITHUB_OUTPUT

    - name: Debug matrix paths
      run: |
        echo "Generated matrix paths: ${{ env.matrix }}"

  build:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJson(env.matrix) }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get names
      id: name
      run: |
        device=$(echo ${{ matrix.path }} | cut -d/ -f2)
        fw=$(echo ${{ matrix.path }} | cut -d/ -f3)
        flavor=$(echo ${{ matrix.path }} | cut -d/ -f4)

        echo "device=$device"
        echo "fw=$fw"
        echo "flavor=$flavor"

        echo "device=${device}" >> $GITHUB_OUTPUT
        echo "fw=${fw}" >> $GITHUB_OUTPUT
        echo "flavor=${flavor}" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gzip tar coreutils

    - name: Create necessary directories
      run: |
        mkdir -p ./repo/IPK_files
        mkdir -p ./repo/usign/build
        mkdir -p ./output

    - name: Copy precompiled usign binary
      run: |
        cp ./usign/build/usign ./repo/usign/build/usign

    - name: Set execute permissions for usign
      run: |
        chmod +x ./repo/usign/build/usign

    - name: Copy precompiled IPKs
      run: |
        find ${{ matrix.path }} -type f -name '*.ipk' -exec cp {} ./repo/IPK_files/ \;

    - name: Generate Packages file
      run: |
        chmod +x ./scripts/generate_packages.sh
        ./scripts/generate_packages.sh

    - name: Compress Packages file
      run: |
        chmod +x ./scripts/compress_packages.sh
        ./scripts/compress_packages.sh

    - name: Generate Packages manifest
      run: |
        chmod +x ./scripts/generate_manifest.sh
        ./scripts/generate_manifest.sh

    - name: Sign Packages file
      env:
        USIGN_PRIVATE_KEY: ${{ secrets.USIGN_PRIVATE_KEY }}
      run: |
        chmod +x ./scripts/sign_packages.sh
        ./scripts/sign_packages.sh ./output/Packages ./output/Packages.sig "$USIGN_PRIVATE_KEY" ./repo/usign/build/usign

    - name: Move files to root directory
      run: |
        mv ./output/* ${{ github.workspace }}
        mv ./repo/IPK_files/* ${{ github.workspace }}

    - name: Output Date
      id: date
      run: |
        date="$(date +'%Y-%m-%d')"
        echo "date=$date"
        echo "date=${date}" >> $GITHUB_OUTPUT

    - name: Upload generated files
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.name.outputs.device }}-${{ steps.name.outputs.fw }}-${{ steps.name.outputs.flavor }}--${{ steps.date.outputs.date }}
        path: |
          ${{ github.workspace }}/Packages
          ${{ github.workspace }}/Packages.gz
          ${{ github.workspace }}/Packages.manifest
          ${{ github.workspace }}/Packages.sig
          ${{ github.workspace }}/*.ipk
        if-no-files-found: error
