name: Generate IPK Repository Files and Upload to S3

on:
  workflow_dispatch:
  push:
    paths:
      - '**.ipk'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - devices/ln6001/fw_v1.0.3.01/enterprise/curated
          - devices/ln6001/fw_v1.0.3.01/enterprise/supported

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get names
      id: name
      run: |
        device=$(echo ${{ matrix.path }} | cut -d/ -f2)
        fw=$(echo ${{ matrix.path }} | cut -d/ -f3)
        flavor=$(echo ${{ matrix.path }} | cut -d/ -f4)
        category=$(echo ${{ matrix.path }} | cut -d/ -f5)
        date=$(date +'%Y-%m-%d')

        echo "device=$device"
        echo "fw=$fw"
        echo "flavor=$flavor"
        echo "category=$category"
        echo "date=$date"

        echo "device=${device}" >> $GITHUB_ENV
        echo "fw=${fw}" >> $GITHUB_ENV
        echo "flavor=${flavor}" >> $GITHUB_ENV
        echo "category=${category}" >> $GITHUB_ENV
        echo "date=${date}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gzip tar coreutils zip awscli

    - name: Create necessary directories
      run: |
        mkdir -p ./output/${{ env.device }}/${{ env.fw }}/${{ env.flavor }}/${{ env.category }}

    - name: Copy precompiled usign binary
      run: |
        cp ./usign/build/usign ./output/usign
        echo "Copied usign binary"

    - name: Set execute permissions for usign
      run: |
        chmod +x ./output/usign
        echo "Set execute permissions for usign"

    - name: Copy precompiled IPKs
      run: |
        echo "Copying IPK files from ${{ matrix.path }} to ./output/${{ env.device }}/${{ env.fw }}/${{ env.flavor }}/${{ env.category }}/"
        find ${{ matrix.path }} -type f -name '*.ipk' -exec cp {} ./output/${{ env.device }}/${{ env.fw }}/${{ env.flavor }}/${{ env.category }}/ \;
        echo "IPK files in ./output/${{ env.device }}/${{ env.fw }}/${{ env.flavor }}/${{ env.category }}/:"
        ls -l ./output/${{ env.device }}/${{ env.fw }}/${{ env.flavor }}/${{ env.category }}/

    - name: Generate Packages file
      run: |
        chmod +x ./scripts/generate_packages.sh
        ./scripts/generate_packages.sh ${{ env.category }}
        echo "Contents of Packages file:"
        cat ./output/${{ env.device }}/${{ env.fw }}/${{ env.flavor }}/${{ env.category }}/Packages

    - name: Compress Packages file
      run: |
        chmod +x ./scripts/compress_packages.sh
        ./scripts/compress_packages.sh

    - name: Generate Packages manifest
      run: |
        chmod +x ./scripts/generate_manifest.sh
        ./scripts/generate_manifest.sh
        echo "Contents of Packages.manifest file:"
        cat ./output/${{ env.device }}/${{ env.fw }}/${{ env.flavor }}/${{ env.category }}/Packages.manifest
      env:
        device: ${{ env.device }}
        fw: ${{ env.fw }}
        flavor: ${{ env.flavor }}
        category: ${{ env.category }}

    - name: Sign Packages file
      env:
        USIGN_PRIVATE_KEY: ${{ secrets.USIGN_PRIVATE_KEY }}
        device: ${{ env.device }}
        fw: ${{ env.fw }}
        flavor: ${{ env.flavor }}
        category: ${{ env.category }}
      run: |
        chmod +x ./scripts/sign_packages.sh
        ./scripts/sign_packages.sh

    - name: Upload individual artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.device }}-${{ env.fw }}-${{ env.flavor }}-${{ env.category }}--${{ env.date }}
        path: ./output/${{ env.device }}/${{ env.fw }}/${{ env.flavor }}/${{ env.category }}/**

  upload-to-s3:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Organize and upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        for artifact in ./artifacts/*; do
          dest_path="s3://wrtrepo-out-test/${artifact##*/}"
          echo "Uploading $artifact to $dest_path"
          aws s3 cp "$artifact" "$dest_path" --recursive --sse AES256
        done

    - name: Create master ZIP file
      run: |
        mkdir -p master_repo/artifacts
        cp -r ./artifacts/* master_repo/artifacts/
        zip -r master_repo.zip master_repo
        echo "Contents of master_repo:"
        ls -R master_repo

    - name: Upload master ZIP file
      uses: actions/upload-artifact@v4
      with:
        name: master_repo
        path: master_repo.zip
