name: Generate IPK Repository Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gzip tar coreutils

    - name: Create necessary directories
      run: |
        mkdir -p ./repo/IPK_files
        mkdir -p ./repo/usign/build
        mkdir -p ./keys
        mkdir -p ./output

    - name: Copy precompiled usign binary
      run: |
        cp ./usign/build/usign ./repo/usign/build/usign

    - name: Set execute permissions for usign
      run: |
        chmod +x ./repo/usign/build/usign

    - name: Debug private key
      run: |
        echo "Contents of the private key file:"
        cat ./keys/openWrtUsign.key

    - name: Run IPK repository generator script
      run: |
        chmod +x ./scripts/gen_repo_files.sh
        ./scripts/gen_repo_files.sh

    - name: Debug output directory
      run: |
        echo "Contents of the output directory:"
        ls -l ./output
        cat ./output/Packages
        cat ./output/Packages.manifest

    - name: Upload generated files
      uses: actions/upload-artifact@v2
      with:
        name: repo-files
        path: ./output/
